### ISSUE TITLE
奔溃问题: Collection was mutated while being enumerated,求解决

### ISSUE THREAD

**Issue by zhonghphuan** [ShawnFoo/FXDanmaku#1]
奔溃位置:
[FXGCDOperationQueue cancelAllOperation] (FXGCDOperationQueue.m:83)
[FXDanmaku emptyData] (FXDanmaku.m:367)
[FXDanmaku stopConsumingData] (FXDanmaku.m:766)
[FXDanmaku consumeData] (FXDanmaku.m:748)
[FXDanmaku startConsuming]_block_invoke (FXDanmaku.m:458)
谢谢

**Comment by ShawnFoo** [comment]
Please upload the system version , device model and full call stack log. Thanks
For now , I think it's the problem of NSHashTable.

**Comment by zhonghphuan** [comment]
the system version:
iOS 10.3.2
iOS 9.2.1
iOS 8.4

device model :iPhone 7 Plus iPhone 6 Plus  iPhone 6s iPhone 6

full call stack log:
1 CoreFoundation 0x181646ff8___exceptionPreprocess + 148
2 libobjc.A.dylib 0x1800a8538_objc_exception_throw + 56
3 CoreFoundation 0x181646a30-[NSException name] + 0
4 Foundation 0x18203838c-[NSConcreteHashTable countByEnumeratingWithState:objects:count:] + 72
5 XXXX 0x10024a870-[FXGCDOperationQueue cancelAllOperation] (FXGCDOperationQueue.m:83)
6 XXXX 0x1002466f4-[FXDanmaku emptyData] (FXDanmaku.m:367)
7 XXXX 0x1002487cc-[FXDanmaku stopConsumingData] (FXDanmaku.m:766)
8 XXXX 0x100248700-[FXDanmaku consumeData] (FXDanmaku.m:748)
9 XXXX 0x100247094___27-[FXDanmaku startConsuming]_block_invoke (FXDanmaku.m:458)
10 libdispatch.dylib 0x1804fe9e0__dispatch_call_block_and_release + 24
11 libdispatch.dylib 0x1804fe9a0__dispatch_client_callout + 16
12 libdispatch.dylib 0x18050cad4__dispatch_queue_serial_drain + 928
13 libdispatch.dylib 0x1805022cc__dispatch_queue_invoke + 884
14 libdispatch.dylib 0x18050cfa8__dispatch_queue_override_invoke + 344
15 libdispatch.dylib 0x18050ea50__dispatch_root_queue_drain + 540
16 libdispatch.dylib 0x18050e7d0__dispatch_worker_thread3 + 124
17 libsystem_pthread.dylib0x180707100__pthread_wqthread + 1096
18 libsystem_pthread.dylib0x180706cac_start_wqthread + 4

main:
1 libsystem_kernel.dylib0x180623224_mach_msg_trap + 8
2 libsystem_kernel.dylib0x18062309c_mach_msg + 72
3 CoreFoundation 0x1815f4e90___CFRunLoopServiceMachPort + 192
4 CoreFoundation 0x1815f2ae4___CFRunLoopRun + 1060
5 CoreFoundation 0x181522da4_CFRunLoopRunSpecific + 424
6 GraphicsServices 0x182f8c074_GSEventRunModal + 100
7 UIKit 0x1877dd058_UIApplicationMain + 208
8 XXXX 0x100078b18_main (main.m:17)
9 libdyld.dylib 0x18053159c_start + 4

Thanks.
